# This is a basic workflow to help you get started with Actions

name: Snake Gmae

# Controls when the workflow will run
on:

  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Repositorio que será utilizado para gerar os arquivos.
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: beneditomanhice #Seu usuario
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - run: git status

      # Para as atualizações.
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          # the output branch we mentioned above
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

                      - nome: Carregar um artefato de construção
  usos: ações/upload-artefato@v4.6.2
  com:
    # Nome do artefato
    nome: # opcional, o padrão é artefato
    # Um arquivo, diretório ou padrão curinga que descreve o que enviar
    caminho:
    # O comportamento desejado se nenhum arquivo for encontrado usando o caminho fornecido.
Opções disponíveis:
  avisar: emitir um aviso, mas não falhar na ação
  erro: falha na ação com uma mensagem de erro
  ignorar: Não emite nenhum aviso ou erro, a ação não falha

    if-no-files-found: # opcional, o padrão é avisar
    # Duração após a qual o artefato irá expirar em dias. 0 significa usar retenção padrão.
Mínimo de 1 dia. Máximo de 90 dias, a menos que seja alterado na página de configurações do repositório.

    dias de retenção: # opcional
    # O nível de compactação do Zlib a ser aplicado ao arquivo de artefato. O valor pode variar de 0 a 9: - 0: Sem compactação - 1: Melhor velocidade - 6: Compactação padrão (igual ao GNU Gzip) - 9: Melhor compactação. Níveis mais altos resultarão em melhor compactação, mas levarão mais tempo para serem concluídos. Para arquivos grandes que não são facilmente compactados, um valor de 0 é recomendado para uploads significativamente mais rápidos.

    nível de compressão: # opcional, o padrão é 6
    # Se verdadeiro, um artefato com um nome correspondente será excluído antes que um novo seja carregado. Se falso, a ação falhará se um artefato com o nome fornecido já existir. Não falhará se o artefato não existir.

    sobrescrever: # opcional, o padrão é falso
    # Se verdadeiro, os arquivos ocultos serão incluídos no artefato. Se falso, os arquivos ocultos serão excluídos do artefato.

    include-hidden-files: # opcional, o padrão é falso
          
